# Generated by Django 5.2.5 on 2025-08-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the activity', max_length=255)),
                ('activity_type', models.CharField(choices=[('MILKING', 'Milking'), ('FEEDING', 'Feeding'), ('HEALTH_CHECK', 'Health Check'), ('VACCINATION', 'Vaccination'), ('BREEDING', 'Breeding'), ('CALVING', 'Calving'), ('WEIGHING', 'Weighing'), ('MEDICATION', 'Medication'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], help_text='Type of activity', max_length=20)),
                ('scheduled_date', models.DateField(help_text='Scheduled date for the activity')),
                ('scheduled_time', models.TimeField(blank=True, help_text='Scheduled time for the activity', null=True)),
                ('start_time', models.DateTimeField(blank=True, help_text='Actual start time of the activity', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Actual end time of the activity', null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', help_text='Current status of the activity', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the activity', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the activity', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost associated with this activity', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
    ]
