# Generated by Django 5.2.5 on 2025-08-20 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('cows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cow',
            field=models.ForeignKey(help_text='Cow associated with this activity', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cows.cow'),
        ),
    ]
