# Generated by Django 5.2.5 on 2025-08-20 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cows', '0002_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of milk production')),
                ('morning_quantity_liters', models.DecimalField(decimal_places=2, default=0, help_text='Morning milk quantity in liters', max_digits=6)),
                ('evening_quantity_liters', models.DecimalField(decimal_places=2, default=0, help_text='Evening milk quantity in liters', max_digits=6)),
                ('total_quantity_liters', models.DecimalField(decimal_places=2, help_text='Total milk quantity for the day in liters', max_digits=6)),
                ('fat_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Fat percentage in the milk', max_digits=4, null=True)),
                ('protein_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Protein percentage in the milk', max_digits=4, null=True)),
                ('quality_rating', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')], help_text='Quality rating of the milk', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the milk production', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cow', models.ForeignKey(help_text='Cow that produced the milk', on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='cows.cow')),
                ('farm', models.ForeignKey(help_text='Farm where the milk was produced', on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Milk Record',
                'verbose_name_plural': 'Milk Records',
                'db_table': 'milk_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
