# Generated by Django 5.2.5 on 2025-08-20 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('milk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='milkrecord',
            name='farmer',
            field=models.ForeignKey(help_text='Farmer who recorded the milk production', limit_choices_to={'role': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='milkrecord',
            unique_together={('cow', 'date')},
        ),
    ]
