# Generated by Django 5.2.5 on 2025-08-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(help_text='Unique identification tag for the cow', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text="Cow's name (optional)", max_length=100, null=True)),
                ('breed', models.CharField(choices=[('HOLSTEIN', 'Holstein'), ('JERSEY', 'Jersey'), ('GUERNSEY', 'Guernsey'), ('AYRSHIRE', 'Ayrshire'), ('BROWN_SWISS', 'Brown Swiss'), ('OTHER', 'Other')], default='HOLSTEIN', help_text='Breed of the cow', max_length=20)),
                ('date_of_birth', models.DateField(help_text="Cow's date of birth")),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Current weight in kilograms', max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SOLD', 'Sold'), ('DECEASED', 'Deceased')], default='ACTIVE', help_text='Current status of the cow', max_length=20)),
                ('is_pregnant', models.BooleanField(default=False, help_text='Whether the cow is currently pregnant')),
                ('last_breeding_date', models.DateField(blank=True, help_text='Date of last breeding', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cow',
                'verbose_name_plural': 'Cows',
                'db_table': 'cows',
                'ordering': ['tag_number'],
            },
        ),
    ]
