# Generated by Django 5.2.5 on 2025-08-20 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cows', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='farm',
            field=models.ForeignKey(help_text='Farm where the cow is located', on_delete=django.db.models.deletion.CASCADE, related_name='cows', to='farms.farm'),
        ),
    ]
