# Generated by Django 5.2.5 on 2025-08-20 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cows', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='farmer',
            field=models.ForeignKey(help_text='Farmer who owns this cow', limit_choices_to={'role': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cows', to=settings.AUTH_USER_MODEL),
        ),
    ]
