# Generated by Django 5.2.5 on 2025-08-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the farm', max_length=255)),
                ('location', models.CharField(help_text='Farm location/address', max_length=500)),
                ('size_acres', models.DecimalField(decimal_places=2, help_text='Farm size in acres', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description of the farm', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the farm is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
                'db_table': 'farms',
                'ordering': ['-created_at'],
            },
        ),
    ]
