# Generated by Django 5.2.5 on 2025-08-20 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='agent',
            field=models.ForeignKey(help_text='Agent responsible for this farm', limit_choices_to={'role': 'AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_farms', to=settings.AUTH_USER_MODEL),
        ),
    ]
